# Generated by Django 3.0.7 on 2020-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=254, verbose_name='Бүтэн Нэр')),
                ('email', models.EmailField(max_length=254, verbose_name='Эмайл Хаяг')),
                ('phone', models.CharField(max_length=12, verbose_name='Утас')),
                ('text', models.TextField(verbose_name='Агуулга')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бидэнтэй Холбогдох',
                'verbose_name_plural': 'Бидэнтэй Холбогдох Жагсаалт',
                'ordering': ('-created',),
            },
        ),
    ]
