# Generated by Django 3.0.7 on 2020-07-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='steamuser',
            name='phone',
        ),
    ]
