# Generated by Django 3.0.7 on 2020-07-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='box1_pic',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='box2_pic',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='box3_pic',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='box4_pic',
        ),
    ]
