# Generated by Django 3.0.7 on 2020-06-14 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Server-ийн нэр')),
                ('pic', models.ImageField(upload_to='servers', verbose_name='Server-ийн зураг')),
            ],
            options={
                'verbose_name': 'Идэвхтэй server',
                'verbose_name_plural': 'Идэвхтэй server - Жагсаалт',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-created',), 'verbose_name': 'Бидэнтэй Холбогдох', 'verbose_name_plural': 'Бидэнтэй Холбогдох - Хүсэлтүүд'},
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='rewards', verbose_name='Шагналын зураг')),
                ('year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('month', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('serName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nesa.ActiveServers')),
            ],
        ),
    ]
