# Generated by Django 3.0.7 on 2020-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
