# Generated by Django 3.0.7 on 2020-07-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0002_auto_20200722_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Имэйл')),
                ('phone_no', models.CharField(max_length=255, verbose_name='Утасны дугаар')),
                ('steamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Steam хэрэглэгч')),
            ],
        ),
    ]
