# Generated by Django 3.0.7 on 2020-07-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0002_auto_20200702_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='box4_text',
        ),
    ]
