# Generated by Django 3.0.7 on 2020-07-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0003_auto_20200706_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='slug',
            field=models.CharField(default='', editable=False, max_length=250, unique=True),
        ),
    ]
