# Generated by Django 3.0.7 on 2020-07-02 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0003_settings_guide_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='guide_vid',
            field=models.FileField(blank=True, default=None, upload_to='settings/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'wmv', 'qt', 'mov'])], verbose_name='Заавар бичлэг'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_no',
            field=models.CharField(default='', max_length=255, verbose_name='Холбоо барих утасны дугаар'),
        ),
    ]
