# Generated by Django 3.0.7 on 2020-07-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0003_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Хэрэглэгчид', 'verbose_name_plural': 'Хэрэглэгчид'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='steamid',
            new_name='steamuser',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Нэр'),
        ),
        migrations.CreateModel(
            name='TempPaymentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nesa.User', verbose_name='Steam хэрэглэгч')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='JSON дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nesa.User', verbose_name='Steam хэрэглэгч')),
            ],
        ),
    ]
