# Generated by Django 3.0.7 on 2020-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0003_auto_20200615_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Сайтын Тохиргоо', editable=False, max_length=250)),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Фэйсбоок')),
                ('twitter', models.URLField(blank=True, default='', verbose_name='Твиттер')),
                ('gmail', models.URLField(blank=True, default='', verbose_name='Цахим Хаяг')),
                ('steam', models.URLField(blank=True, default='', verbose_name='Цахим Хаяг')),
                ('youtube', models.URLField(blank=True, default='', verbose_name='Цахим Хаяг')),
                ('twitch', models.URLField(blank=True, default='', verbose_name='Цахим Хаяг')),
            ],
            options={
                'verbose_name': 'Вэб Сайтын Тохиргоо',
                'verbose_name_plural': 'Вэб Сайтын Тохиргоо',
            },
        ),
    ]
