# Generated by Django 3.0.7 on 2020-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0004_auto_20200722_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temppaymentid',
            old_name='tempid',
            new_name='bill_no',
        ),
        migrations.AddField(
            model_name='temppaymentid',
            name='month',
            field=models.IntegerField(default=None),
        ),
    ]
