# Generated by Django 3.0.7 on 2020-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0004_auto_20200702_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(editable=False, max_length=254, verbose_name='Эмайл Хаяг'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='fullName',
            field=models.CharField(editable=False, max_length=254, verbose_name='Бүтэн Нэр'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(editable=False, max_length=12, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(editable=False, verbose_name='Агуулга'),
        ),
    ]
