# Generated by Django 3.0.7 on 2020-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='gmail',
            field=models.URLField(blank=True, default='', verbose_name='Gmail хаяг'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='steam',
            field=models.URLField(blank=True, default='', verbose_name='Steam хаяг'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitch',
            field=models.URLField(blank=True, default='', verbose_name='Twitch хаяг '),
        ),
        migrations.AlterField(
            model_name='settings',
            name='youtube',
            field=models.URLField(blank=True, default='', verbose_name='Youtube хаяг'),
        ),
    ]
