# Generated by Django 3.0.7 on 2020-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0005_auto_20200616_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default='', upload_to='settings', verbose_name='Сайтын лого'),
        ),
    ]
