# Generated by Django 3.0.7 on 2020-07-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0005_auto_20200707_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='slug',
            field=models.CharField(default='', editable=False, max_length=250, unique=True),
        ),
    ]
