# Generated by Django 3.0.7 on 2020-07-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0006_auto_20200722_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaymentid',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Нэр'),
        ),
    ]
