# Generated by Django 3.0.7 on 2020-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0007_temppaymentid_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('expDate', models.CharField(max_length=255)),
            ],
        ),
    ]
