# Generated by Django 3.0.7 on 2020-07-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0007_auto_20200713_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='box1_title',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 1-Гарчиг'),
        ),
    ]
