# Generated by Django 3.0.7 on 2020-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0008_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='steamid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
