# Generated by Django 3.0.7 on 2020-07-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0008_auto_20200714_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='box1_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 1-Текст'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='box2_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 2-Текст'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='box2_title',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 2-Гарчиг'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='box3_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 3-Текст'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='box3_title',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 3-Гарчиг'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='box4_title',
            field=models.TextField(blank=True, max_length=255, verbose_name='Box 4-Гарчиг'),
        ),
    ]
