# Generated by Django 3.0.7 on 2020-07-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0009_auto_20200714_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Нэр')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Нэр')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='Нэр')),
                ('pic', models.ImageField(blank=True, default='', upload_to='news', verbose_name='Зураг')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(default='', editable=False, max_length=255, verbose_name='Нэр')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nesa.NewsCategory', verbose_name='Category')),
            ],
        ),
    ]
