# Generated by Django 3.0.7 on 2020-07-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0009_auto_20200724_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='expDate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
