# Generated by Django 3.0.7 on 2020-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0010_auto_20200724_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='registered',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
