# Generated by Django 3.0.7 on 2020-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0011_auto_20200716_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(default='', verbose_name='Мэдээ'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='slug'),
        ),
    ]
