# Generated by Django 3.0.7 on 2020-07-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0012_auto_20200716_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
