# Generated by Django 3.0.7 on 2020-07-25 08:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0012_paymenthistory_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
