# Generated by Django 3.0.7 on 2020-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0013_auto_20200725_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='data',
            field=models.TextField(verbose_name='JSON дата'),
        ),
    ]
