# Generated by Django 3.0.7 on 2020-07-25 08:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0014_auto_20200725_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
