# Generated by Django 3.0.7 on 2020-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0016_auto_20200717_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(default='', upload_to='news', verbose_name='Зураг'),
        ),
    ]
