# Generated by Django 3.0.8 on 2020-08-01 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0016_auto_20200725_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='month',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
