# Generated by Django 3.0.7 on 2020-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='steamid',
            field=models.CharField(default='', max_length=255, verbose_name='Steam ID'),
        ),
    ]
