# Generated by Django 3.0.7 on 2020-07-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0019_auto_20200717_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
