# Generated by Django 3.0.7 on 2020-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0020_auto_20200717_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.DecimalField(decimal_places=4, max_digits=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
