# Generated by Django 3.0.7 on 2020-07-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0021_auto_20200717_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='slug'),
        ),
    ]
