# Generated by Django 3.0.7 on 2020-06-15 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0002_auto_20200614_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='month',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
